/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2013-2015, Maxim Roncacé <mproncace@lapis.blue>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package net.caseif.ttt.util;

import com.google.common.collect.BiMap;
import org.bukkit.Material;

/**
 * Utility class for converting between Minecraft names and Bukkit materials.
 * Stolen/repurposed from Pore.
 */
public final class MaterialConverter {

	//TODO: the compiler seems to be upset about my use of generics but it works fine and I really cbf to fix it right now
	@SuppressWarnings("unchecked")
	public static final BiMap<Material, String> ITEM_TYPE_CONVERTER = BiMapBuilder.<Material, String>builder()
			.put(Material.STONE, "STONE")
			.put(Material.GRASS, "GRASS")
			.put(Material.DIRT, "DIRT")
			.put(Material.COBBLESTONE, "COBBLESTONE")
			.put(Material.WOOD, "PLANKS")
			.put(Material.SAPLING, "SAPLING")
			.put(Material.BEDROCK, "BEDROCK")
			.put(Material.SAND, "SAND")
			.put(Material.GRAVEL, "GRAVEL")
			.put(Material.GOLD_ORE, "GOLD_ORE")
			.put(Material.IRON_ORE, "IRON_ORE")
			.put(Material.COAL_ORE, "COAL_ORE")
			.put(Material.LOG, "LOG")
			.put(Material.LOG_2, "LOG2")
			.put(Material.LEAVES, "LEAVES")
			.put(Material.LEAVES_2, "LEAVES2")
			.put(Material.SPONGE, "SPONGE")
			.put(Material.GLASS, "GLASS")
			.put(Material.LAPIS_ORE, "LAPIS_ORE")
			.put(Material.LAPIS_BLOCK, "LAPIS_BLOCK") // <3
			.put(Material.DISPENSER, "DISPENSER")
			.put(Material.SANDSTONE, "SANDSTONE")
			.put(Material.NOTE_BLOCK, "NOTEBLOCK")
			.put(Material.POWERED_RAIL, "GOLDEN_RAIL")
			.put(Material.DETECTOR_RAIL, "DETECTOR_RAIL")
			.put(Material.PISTON_STICKY_BASE, "STICKY_PISTON")
			.put(Material.WEB, "WEB")
			.put(Material.LONG_GRASS, "TALLGRASS")
			.put(Material.DEAD_BUSH, "DEADBUSH")
			.put(Material.PISTON_BASE, "PISTON")
			.put(Material.WOOL, "WOOL")
			.put(Material.YELLOW_FLOWER, "YELLOW_FLOWER")
			.put(Material.RED_ROSE, "RED_FLOWER")
			.put(Material.BROWN_MUSHROOM, "BROWN_MUSHROOM")
			.put(Material.RED_MUSHROOM, "RED_MUSHROOM")
			.put(Material.GOLD_BLOCK, "GOLD_BLOCK")
			.put(Material.IRON_BLOCK, "IRON_BLOCK")
			.put(Material.STEP, "STONE_SLAB")
			.put(Material.BRICK, "BRICK_BLOCK")
			.put(Material.TNT, "TNT")
			.put(Material.BOOKSHELF, "BOOKSHELF")
			.put(Material.MOSSY_COBBLESTONE, "MOSSY_COBBLESTONE")
			.put(Material.OBSIDIAN, "OBSIDIAN")
			.put(Material.TORCH, "TORCH")
			.put(Material.MOB_SPAWNER, "MOB_SPAWNER")
			.put(Material.WOOD_STAIRS, "OAK_STAIRS")
			.put(Material.CHEST, "CHEST")
			.put(Material.DIAMOND_ORE, "DIAMOND_ORE")
			.put(Material.DIAMOND_BLOCK, "DIAMOND_BLOCK")
			.put(Material.WORKBENCH, "CRAFTING_TABLE")
			.put(Material.SOIL, "FARMLAND")
			.put(Material.FURNACE, "FURNACE")
			.put(Material.BURNING_FURNACE, "LIT_FURNACE")
			.put(Material.LADDER, "LADDER")
			.put(Material.RAILS, "RAIL")
			.put(Material.COBBLESTONE_STAIRS, "STONE_STAIRS")
			.put(Material.LEVER, "LEVER")
			.put(Material.STONE_PLATE, "STONE_PRESSURE_PLATE")
			.put(Material.WOOD_PLATE, "WOODEN_PRESSURE_PLATE")
			.put(Material.REDSTONE_ORE, "REDSTONE_ORE")
			.put(Material.REDSTONE_TORCH_ON, "REDSTONE_TORCH")
			.put(Material.STONE_BUTTON, "STONE_BUTTON")
			.put(Material.SNOW, "SNOW_LAYER")
			.put(Material.ICE, "ICE")
			.put(Material.SNOW_BLOCK, "SNOW")
			.put(Material.CACTUS, "CACTUS")
			.put(Material.CLAY, "CLAY")
			.put(Material.JUKEBOX, "JUKEBOX")
			.put(Material.FENCE, "FENCE")
			.put(Material.SPRUCE_FENCE, "SPRUCE_FENCE")
			.put(Material.BIRCH_FENCE, "BIRCH_FENCE")
			.put(Material.JUNGLE_FENCE, "JUNGLE_FENCE")
			.put(Material.DARK_OAK_FENCE, "DARK_OAK_FENCE")
			.put(Material.ACACIA_FENCE, "ACACIA_FENCE")
			.put(Material.PUMPKIN, "PUMPKIN")
			.put(Material.NETHERRACK, "NETHERRACK")
			.put(Material.SOUL_SAND, "SOUL_SAND")
			.put(Material.GLOWSTONE, "GLOWSTONE")
			.put(Material.JACK_O_LANTERN, "LIT_PUMPKIN")
			.put(Material.TRAP_DOOR, "TRAPDOOR")
			.put(Material.MONSTER_EGGS, "MONSTER_EGG")
			.put(Material.SMOOTH_BRICK, "STONEBRICK")
			.put(Material.HUGE_MUSHROOM_1, "BROWN_MUSHROOM_BLOCK")
			.put(Material.HUGE_MUSHROOM_2, "RED_MUSHROOM_BLOCK")
			.put(Material.IRON_FENCE, "IRON_BARS")
			.put(Material.THIN_GLASS, "GLASS_PANE")
			.put(Material.MELON_BLOCK, "MELON_BLOCK")
			.put(Material.VINE, "VINE")
			.put(Material.FENCE_GATE, "FENCE_GATE")
			.put(Material.SPRUCE_FENCE_GATE, "SPRUCE_FENCE_GATE")
			.put(Material.BIRCH_FENCE_GATE, "BIRCH_FENCE_GATE")
			.put(Material.JUNGLE_FENCE_GATE, "JUNGLE_FENCE_GATE")
			.put(Material.DARK_OAK_FENCE_GATE, "DARK_OAK_FENCE_GATE")
			.put(Material.ACACIA_FENCE_GATE, "ACACIA_FENCE_GATE")
			.put(Material.BRICK_STAIRS, "BRICK_STAIRS")
			.put(Material.SMOOTH_STAIRS, "STONE_BRICK_STAIRS")
			.put(Material.MYCEL, "MYCELIUM")
			.put(Material.WATER_LILY, "WATERLILY")
			.put(Material.NETHER_BRICK, "NETHER_BRICK")
			.put(Material.NETHER_FENCE, "NETHER_BRICK_FENCE")
			.put(Material.NETHER_BRICK_STAIRS, "NETHER_BRICK_STAIRS")
			.put(Material.ENCHANTMENT_TABLE, "ENCHANTING_TABLE")
			.put(Material.ENDER_PORTAL_FRAME, "END_PORTAL_FRAME")
			.put(Material.ENDER_STONE, "END_STONE")
			.put(Material.DRAGON_EGG, "DRAGON_EGG")
			.put(Material.REDSTONE_LAMP_OFF, "REDSTONE_LAMP")
			.put(Material.WOOD_STEP, "WOODEN_SLAB")
			.put(Material.SANDSTONE_STAIRS, "SANDSTONE_STAIRS")
			.put(Material.EMERALD_ORE, "EMERALD_ORE")
			.put(Material.ENDER_CHEST, "ENDER_CHEST")
			.put(Material.TRIPWIRE_HOOK, "TRIPWIRE_HOOK")
			.put(Material.EMERALD_BLOCK, "EMERALD_BLOCK")
			.put(Material.SPRUCE_WOOD_STAIRS, "SPRUCE_STAIRS")
			.put(Material.BIRCH_WOOD_STAIRS, "BIRCH_STAIRS")
			.put(Material.JUNGLE_WOOD_STAIRS, "JUNGLE_STAIRS")
			.put(Material.COMMAND, "COMMAND_BLOCK")
			.put(Material.BEACON, "BEACON")
			.put(Material.COBBLE_WALL, "COBBLESTONE_WALL")
			.put(Material.WOOD_BUTTON, "WOODEN_BUTTON")
			.put(Material.ANVIL, "ANVIL")
			.put(Material.TRAPPED_CHEST, "TRAPPED_CHEST")
			.put(Material.GOLD_PLATE, "LIGHT_WEIGHTED_PRESSURE_PLATE")
			.put(Material.IRON_PLATE, "HEAVY_WEIGHTED_PRESSURE_PLATE")
			.put(Material.DAYLIGHT_DETECTOR, "DAYLIGHT_DETECTOR")
			.put(Material.REDSTONE_BLOCK, "REDSTONE_BLOCK")
			.put(Material.QUARTZ_ORE, "QUARTZ_ORE")
			.put(Material.HOPPER, "HOPPER")
			.put(Material.QUARTZ_BLOCK, "QUARTZ_BLOCK")
			.put(Material.QUARTZ_STAIRS, "QUARTZ_STAIRS")
			.put(Material.ACTIVATOR_RAIL, "ACTIVATOR_RAIL")
			.put(Material.DROPPER, "DROPPER")
			.put(Material.STAINED_CLAY, "STAINED_HARDENED_CLAY")
			.put(Material.BARRIER, "BARRIER")
			.put(Material.IRON_TRAPDOOR, "IRON_TRAPDOOR")
			.put(Material.HAY_BLOCK, "HAY_BLOCK")
			.put(Material.CARPET, "CARPET")
			.put(Material.HARD_CLAY, "HARDENED_CLAY")
			.put(Material.COAL_BLOCK, "COAL_BLOCK")
			.put(Material.PACKED_ICE, "PACKED_ICE")
			.put(Material.ACACIA_STAIRS, "ACACIA_STAIRS")
			.put(Material.DARK_OAK_STAIRS, "DARK_OAK_STAIRS")
			.put(Material.SLIME_BLOCK, "SLIME")
			.put(Material.DOUBLE_PLANT, "DOUBLE_PLANT")
			.put(Material.STAINED_GLASS, "STAINED_GLASS")
			.put(Material.STAINED_GLASS_PANE, "STAINED_GLASS_PANE")
			.put(Material.PRISMARINE, "PRISMARINE")
			.put(Material.SEA_LANTERN, "SEA_LANTERN")
			.put(Material.RED_SANDSTONE, "RED_SANDSTONE")
			.put(Material.RED_SANDSTONE_STAIRS, "RED_SANDSTONE_STAIRS")
			.put(Material.STONE_SLAB2, "STONE_SLAB2")
			.put(Material.IRON_SPADE, "IRON_SHOVEL")
			.put(Material.IRON_PICKAXE, "IRON_PICKAXE")
			.put(Material.IRON_AXE, "IRON_AXE")
			.put(Material.FLINT_AND_STEEL, "FLINT_AND_STEEL")
			.put(Material.APPLE, "APPLE")
			.put(Material.BOW, "BOW")
			.put(Material.ARROW, "ARROW")
			.put(Material.COAL, "COAL")
			.put(Material.DIAMOND, "DIAMOND")
			.put(Material.IRON_INGOT, "IRON_INGOT")
			.put(Material.GOLD_INGOT, "GOLD_INGOT")
			.put(Material.IRON_SWORD, "IRON_SWORD")
			.put(Material.WOOD_SWORD, "WOODEN_SWORD")
			.put(Material.WOOD_SPADE, "WOODEN_SHOVEL")
			.put(Material.WOOD_PICKAXE, "WOODEN_PICKAXE")
			.put(Material.WOOD_AXE, "WOODEN_AXE")
			.put(Material.STONE_SWORD, "STONE_SWORD")
			.put(Material.STONE_SPADE, "STONE_SHOVEL")
			.put(Material.STONE_PICKAXE, "STONE_PICKAXE")
			.put(Material.STONE_AXE, "STONE_AXE")
			.put(Material.DIAMOND_SWORD, "DIAMOND_SWORD")
			.put(Material.DIAMOND_SPADE, "DIAMOND_SHOVEL")
			.put(Material.DIAMOND_PICKAXE, "DIAMOND_PICKAXE")
			.put(Material.DIAMOND_AXE, "DIAMOND_AXE")
			.put(Material.STICK, "STICK")
			.put(Material.BOWL, "BOWL")
			.put(Material.MUSHROOM_SOUP, "MUSHROOM_STEW")
			.put(Material.GOLD_SWORD, "GOLDEN_SWORD")
			.put(Material.GOLD_SPADE, "GOLDEN_SHOVEL")
			.put(Material.GOLD_PICKAXE, "GOLDEN_PICKAXE")
			.put(Material.GOLD_AXE, "GOLDEN_AXE")
			.put(Material.STRING, "STRING")
			.put(Material.FEATHER, "FEATHER")
			.put(Material.SULPHUR, "GUNPOWDER")
			.put(Material.WOOD_HOE, "WOODEN_HOE")
			.put(Material.STONE_HOE, "STONE_HOE")
			.put(Material.IRON_HOE, "IRON_HOE")
			.put(Material.DIAMOND_HOE, "DIAMOND_HOE")
			.put(Material.GOLD_HOE, "GOLDEN_HOE")
			.put(Material.SEEDS, "WHEAT_SEEDS")
			.put(Material.WHEAT, "WHEAT")
			.put(Material.BREAD, "BREAD")
			.put(Material.LEATHER_HELMET, "LEATHER_HELMET")
			.put(Material.LEATHER_CHESTPLATE, "LEATHER_CHESTPLATE")
			.put(Material.LEATHER_LEGGINGS, "LEATHER_LEGGINGS")
			.put(Material.LEATHER_BOOTS, "LEATHER_BOOTS")
			.put(Material.CHAINMAIL_HELMET, "CHAINMAIL_HELMET")
			.put(Material.CHAINMAIL_CHESTPLATE, "CHAINMAIL_CHESTPLATE")
			.put(Material.CHAINMAIL_LEGGINGS, "CHAINMAIL_LEGGINGS")
			.put(Material.CHAINMAIL_BOOTS, "CHAINMAIL_BOOTS")
			.put(Material.IRON_HELMET, "IRON_HELMET")
			.put(Material.IRON_CHESTPLATE, "IRON_CHESTPLATE")
			.put(Material.IRON_LEGGINGS, "IRON_LEGGINGS")
			.put(Material.IRON_BOOTS, "IRON_BOOTS")
			.put(Material.DIAMOND_HELMET, "DIAMOND_HELMET")
			.put(Material.DIAMOND_CHESTPLATE, "DIAMOND_CHESTPLATE")
			.put(Material.DIAMOND_LEGGINGS, "DIAMOND_LEGGINGS")
			.put(Material.DIAMOND_BOOTS, "DIAMOND_BOOTS")
			.put(Material.GOLD_HELMET, "GOLDEN_HELMET")
			.put(Material.GOLD_CHESTPLATE, "GOLDEN_CHESTPLATE")
			.put(Material.GOLD_LEGGINGS, "GOLDEN_LEGGINGS")
			.put(Material.GOLD_BOOTS, "GOLDEN_BOOTS")
			.put(Material.FLINT, "FLINT")
			.put(Material.PORK, "PORKCHOP")
			.put(Material.GRILLED_PORK, "COOKED_PORKCHOP")
			.put(Material.PAINTING, "PAINTING")
			.put(Material.GOLDEN_APPLE, "GOLDEN_APPLE")
			.put(Material.SIGN, "SIGN")
			.put(Material.WOOD_DOOR, "WOODEN_DOOR")
			.put(Material.BUCKET, "BUCKET")
			.put(Material.WATER_BUCKET, "WATER_BUCKET")
			.put(Material.LAVA_BUCKET, "LAVA_BUCKET")
			.put(Material.MINECART, "MINECART")
			.put(Material.SADDLE, "SADDLE")
			.put(Material.IRON_DOOR, "IRON_DOOR")
			.put(Material.REDSTONE, "REDSTONE")
			.put(Material.SNOW_BALL, "SNOWBALL")
			.put(Material.BOAT, "BOAT")
			.put(Material.LEATHER, "LEATHER")
			.put(Material.MILK_BUCKET, "MILK_BUCKET")
			.put(Material.CLAY_BRICK, "BRICK")
			.put(Material.CLAY_BALL, "CLAY_BALL")
			.put(Material.SUGAR_CANE, "REEDS")
			.put(Material.PAPER, "PAPER")
			.put(Material.BOOK, "BOOK")
			.put(Material.SLIME_BALL, "SLIME_BALL")
			.put(Material.STORAGE_MINECART, "CHEST_MINECART")
			.put(Material.POWERED_MINECART, "FURNACE_MINECART")
			.put(Material.EGG, "EGG")
			.put(Material.COMPASS, "COMPASS")
			.put(Material.FISHING_ROD, "FISHING_ROD")
			.put(Material.WATCH, "CLOCK")
			.put(Material.GLOWSTONE_DUST, "GLOWSTONE_DUST")
			.put(Material.RAW_FISH, "FISH")
			.put(Material.COOKED_FISH, "COOKED_FISH")
			.put(Material.INK_SACK, "DYE")
			.put(Material.BONE, "BONE")
			.put(Material.SUGAR, "SUGAR")
			.put(Material.CAKE, "CAKE")
			.put(Material.BED, "BED")
			.put(Material.DIODE, "REPEATER")
			.put(Material.COOKIE, "COOKIE")
			.put(Material.MAP, "FILLED_MAP")
			.put(Material.SHEARS, "SHEARS")
			.put(Material.MELON, "MELON")
			.put(Material.PUMPKIN_SEEDS, "PUMPKIN_SEEDS")
			.put(Material.MELON_SEEDS, "MELON_SEEDS")
			.put(Material.RAW_BEEF, "BEEF")
			.put(Material.COOKED_BEEF, "COOKED_BEEF")
			.put(Material.RAW_CHICKEN, "CHICKEN")
			.put(Material.COOKED_CHICKEN, "COOKED_CHICKEN")
			.put(Material.ROTTEN_FLESH, "ROTTEN_FLESH")
			.put(Material.ENDER_PEARL, "ENDER_PEARL")
			.put(Material.BLAZE_ROD, "BLAZE_ROD")
			.put(Material.GHAST_TEAR, "GHAST_TEAR")
			.put(Material.GOLD_NUGGET, "GOLD_NUGGET")
			.put(Material.NETHER_WARTS, "NETHER_WART")
			.put(Material.POTION, "POTION")
			.put(Material.GLASS_BOTTLE, "GLASS_BOTTLE")
			.put(Material.SPIDER_EYE, "SPIDER_EYE")
			.put(Material.FERMENTED_SPIDER_EYE, "FERMENTED_SPIDER_EYE")
			.put(Material.BLAZE_POWDER, "BLAZE_POWDER")
			.put(Material.MAGMA_CREAM, "MAGMA_CREAM")
			.put(Material.BREWING_STAND_ITEM, "BREWING_STAND")
			.put(Material.CAULDRON_ITEM, "CAULDRON")
			.put(Material.EYE_OF_ENDER, "ENDER_EYE")
			.put(Material.SPECKLED_MELON, "SPECKLED_MELON")
			.put(Material.MONSTER_EGG, "SPAWN_EGG")
			.put(Material.EXP_BOTTLE, "EXPERIENCE_BOTTLE")
			.put(Material.FIREBALL, "FIRE_CHARGE")
			.put(Material.BOOK_AND_QUILL, "WRITABLE_BOOK")
			.put(Material.WRITTEN_BOOK, "WRITTEN_BOOK")
			.put(Material.EMERALD, "EMERALD")
			.put(Material.ITEM_FRAME, "ITEM_FRAME")
			.put(Material.FLOWER_POT_ITEM, "FLOWER_POT")
			.put(Material.CARROT_ITEM, "CARROT")
			.put(Material.POTATO_ITEM, "POTATO")
			.put(Material.BAKED_POTATO, "BAKED_POTATO")
			.put(Material.POISONOUS_POTATO, "POISONOUS_POTATO")
			.put(Material.EMPTY_MAP, "MAP")
			.put(Material.GOLDEN_CARROT, "GOLDEN_CARROT")
			.put(Material.SKULL_ITEM, "SKULL")
			.put(Material.CARROT_STICK, "CARROT_ON_A_STICK")
			.put(Material.NETHER_STAR, "NETHER_STAR")
			.put(Material.PUMPKIN_PIE, "PUMPKIN_PIE")
			.put(Material.FIREWORK, "FIREWORKS")
			.put(Material.FIREWORK_CHARGE, "FIREWORK_CHARGE")
			.put(Material.ENCHANTED_BOOK, "ENCHANTED_BOOK")
			.put(Material.REDSTONE_COMPARATOR, "COMPARATOR")
			.put(Material.NETHER_BRICK_ITEM, "NETHERBRICK")
			.put(Material.QUARTZ, "QUARTZ")
			.put(Material.EXPLOSIVE_MINECART, "TNT_MINECART")
			.put(Material.HOPPER_MINECART, "HOPPER_MINECART")
			.put(Material.PRISMARINE_SHARD, "PRISMARINE_SHARD")
			.put(Material.PRISMARINE_CRYSTALS, "PRISMARINE_CRYSTALS")
			.put(Material.RABBIT, "RABBIT")
			.put(Material.COOKED_RABBIT, "COOKED_RABBIT")
			.put(Material.RABBIT_STEW, "RABBIT_STEW")
			.put(Material.RABBIT_FOOT, "RABBIT_FOOT")
			.put(Material.RABBIT_HIDE, "RABBIT_HIDE")
			.put(Material.ARMOR_STAND, "ARMOR_STAND")
			.put(Material.IRON_BARDING, "IRON_HORSE_ARMOR")
			.put(Material.GOLD_BARDING, "GOLDEN_HORSE_ARMOR")
			.put(Material.DIAMOND_BARDING, "DIAMOND_HORSE_ARMOR")
			.put(Material.LEASH, "LEAD")
			.put(Material.NAME_TAG, "NAME_TAG")
			.put(Material.COMMAND_MINECART, "COMMAND_BLOCK_MINECART")
			.put(Material.MUTTON, "MUTTON")
			.put(Material.COOKED_MUTTON, "COOKED_MUTTON")
			.put(Material.BANNER, "BANNER")
			.put(Material.SPRUCE_DOOR_ITEM, "SPRUCE_DOOR")
			.put(Material.BIRCH_DOOR_ITEM, "BIRCH_DOOR")
			.put(Material.JUNGLE_DOOR_ITEM, "JUNGLE_DOOR")
			.put(Material.ACACIA_DOOR_ITEM, "ACACIA_DOOR")
			.put(Material.DARK_OAK_DOOR_ITEM, "DARK_OAK_DOOR")
			.put(Material.GOLD_RECORD, "RECORD_13")
			.put(Material.GREEN_RECORD, "RECORD_CAT")
			.put(Material.RECORD_3, "RECORD_BLOCKS")
			.put(Material.RECORD_4, "RECORD_CHIRP")
			.put(Material.RECORD_5, "RECORD_FAR")
			.put(Material.RECORD_6, "RECORD_MALL")
			.put(Material.RECORD_7, "RECORD_MELLOHI")
			.put(Material.RECORD_8, "RECORD_STAL")
			.put(Material.RECORD_9, "RECORD_STRAD")
			.put(Material.RECORD_10, "RECORD_WARD")
			.put(Material.RECORD_11, "RECORD_11")
			.put(Material.RECORD_12, "RECORD_WAIT")
			.build();

	public static String getNotchName(Material material) {
		return ITEM_TYPE_CONVERTER.get(material);
	}

	public static Material fromNotchName(String type) {
		return ITEM_TYPE_CONVERTER.inverse().get(type);
	}

}
