# ##################### #
# # TTT Configuration # #
# ##################### #

# See http://ttt.badking.net/config-and-commands/convars#TOC-Karma
# for more detailed descriptions of certain config settings.

##################
# Round Settings #
##################

# The number of players required for a round to automtically enter its preparation period.
minimum-players: 3

# The maximum number of players permitted in a round (set to -1 for no limit).
maximum-players: 32

# The duration of the "preparation" period, before roles are assigned and the round fully starts.
preptime-seconds: 60

# The duration of the round after the preparation period when Haste Mode is disabled.
roundtime-seconds: 360

# The duration of the period after the round has ended but before it has reset.
posttime-seconds: 15

# Whether to enable Haste Mode. In Haste Mode, the initial round time is short. Every death increases it by some amount.
# Puts pressure on traitors to keep things moving, which is more interesting for the innocent players.
haste: true

# Replaces roundtime-seconds when Haste Mode is on. Sets the initial time limit.
haste-starting-seconds: 240

# The number of seconds to be added to the round time for each innocent death while in Haste Mode.
haste-seconds-per-death: 30

# Whether players may join rounds in-progress as spectators.
allow-join-as-spectator: true

# When true, victory messages (e.g. "The traitors won!" will be broadcast to all players on the server.
#   (Note: this was the standard behavior until v0.10.)
# When false, they will only be sent to players who were in the particular round.
broadcast-win-messages-to-server: false

##############################
# Traitor/Detective Settings #
##############################

# The ratio of traitors to innocents as a decimal.
traitor-pct: 0.25

# The ratio of detectives to other players.
detective-pct: 0.13

# The minimum number of players required for a detective to be assigned in a round.
# This will override the value of detective-pct if the minimum count is reached.
detective-min-players: 10

# The number of seconds required for the DNA scanner to charge (update).
# (Vanilla TTT uses 25 as default, but also displays the exact location rather than just the direction.)
scanner-charge-time: 7.5

# Maximum range in meters within which a DNA sample of the killer is planted on the corpse of the victim.
killer-dna-range: 10

# The time in seconds DNA samples last for when the killer is 0 meters from the victim.
# When the killer is further, the time will be decreased.
killer-dna-basetime: 100

####################
# Command Settings #
####################

# TTT can run commands on certain events. These commands may be defined below as YAML lists.
# All commands will be executed following the conclusion of their respective events.
# All commands may include the sequence %a, which will be replaced with the ID of the arena involved in the event.

# Join and leave commands are run once per event. They *must* include the sequence %p, which will be replaced with the
# username of the player involved in the event.

# Commands executed when a player joins a round.
player-join-cmds: []

# Commands executed when a player leaves a round.
player-leave-cmds: []

# End status commands will be run once per player in the round involved in the event. They *must* include the
# sequence %p, which will be replaced with the respective username of each player involved the event.

# Commands executed upon all players who win a round.
player-win-cmds: []

# Commands executed upon all players who lose a round.
player-lose-cmds: []

# The following keys define commands which will be executed at the start of the cooldown period.
# In the interest of not documenting each key individually:
#
# player-win-x-cmds: executed upon players who win a round.
# player-lose-x-cmds: executed upon players who win a round.
#
# player-x-innocent-cmds: executed upon players who win/lose a round as an innocent, including detectives.
# player-x-innocentnd-cmds: executed upon players who win/lose a round as an innocent, *not* including detectives.
# player-x-detective-cmds: executed upon players who win/lose a round as a detective.
# player-x-traitor-cmds: executed upon players who win/lose a round as a traitor.

player-win-innocent-cmds: []
player-win-innocentnd-cmds: []
player-win-detective-cmds: []
player-win-traitor-cmds: []
player-lose-innocent-cmds: []
player-lose-innocentnd-cmds: []
player-lose-detective-cmds: []
player-lose-traitor-cmds: []

# Lifecycle commands will be run once per event if they do not include the sequence %p. If they do, they will be
# run once per player in the round involved in the event, and the sequence will be replaced with each respective player
# name.

# Commands executed when the round enters its preparation stage.
round-prepare-cmds: []

# Commands executed when the round enters its playing stage following preparation.
round-start-cmds: []

# Commands executed when the round enters its cooldown stage.
round-cooldown-cmds: []

# Commands executed when the round has concluded its cooldown stage.
round-end-cmds: []

##################
# Title Settings #
##################

# Whether TTT should send titles to players on round start and end.
# This will not do anything on Minecraft versions prior to 1.8.
send-titles: true

# Whether status titles (e.g. "You are a traitor!") should be sent as full-sized titles.
# If false (default), subtitles will be sent instead.
# Setting this to true may cause the title to obstruct the player's screen.
large-status-titles: false

# Whether status titles (e.g. "The traitors won!") should be sent as full-sized titles.
# If false (default), subtitles will be sent instead.
# Setting this to true may cause the title to obstruct the player's screen and additionally may
# cause the title to not fit on the screen for certain locales (such as de_DE).
large-victory-titles: false

###################
# Weapon Settings #
###################

# The item to use as a crowbar. This should be a raw Material enum value.
# See here for all valid values: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
crowbar-item: IRON_SWORD

# The same as crowbar-item, but for pre-1.13 servers.
#Note that the Material registry was overhauled in the 1.13 update.
crowbar-item-legacy: IRON_SWORD

# The item to use as a gun. This should be a raw Material enum value.
# See here for all valid values: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# The default value is IRON_HORSE_ARMOR.
gun-item: IRON_HORSE_ARMOR

# The same as gun-item, but for pre-1.13 servers.
##Note that the Material registry was overhauled in the 1.13 update.
gun-item-legacy: IRON_BARDING

# The amount of damage (in half-hearts) each hit with a crowbar should do.
crowbar-damage: 5

# Whether ammunition is required to use guns.
require-ammo-for-guns: true

# The number of arrows given to players on round start.
initial-ammo: 55

##################
# Karma Settings #
##################

# When strict is off, the damage penalty is very low when people stay above 800.
# However, beyond this limit it will follow a more parabolic curve, dropping more severely the lower the player's karma.
karma-strict: true

# The initial karma assigned to players. This will be clamped to karma-max.
karma-starting: 1000

# The maximum karma a player may hold at a given time.
# (After this is reached, the player will not receive karma until they go below it again.)
karma-max: 1000

# The ratio used in the formula used to determine the karma penalty for damaging an ally (0-1).
karma-ratio: 0.001

# From the official TTT documentation:
#
# All karma penalties are based on damage dealt. The kill penalty is just an extra amount of "damage" dealt
# when you kill someone. So if this was 100, and you headshot someone with a rifle, it would penalise you as
# if you dealt 200 damage.
#
# Note that in Minecraft, the maximum amount of health one may have is 20 (10 hearts).
karma-kill-penalty: 3

# The amount of karma allocated to each player on round end.
karma-round-increment: 5

# The amount of karma allocated on round end to each player who avoided friendly fire.
karma-clean-bonus: 30

# From the official TTT documentation:
#
# When a player's Karma is above the starting level (meaning the karma max has been configured to be higher than
# that), all his karma increases will be reduced based on how far his karma is above that starting level. So it
# goes up slower the higher it is.
karma-clean-half: 0.25

# The ratio used in the formula used to determine the karma reward to innocents for damaging a traitor (0-1).
karma-traitordmg-ratio: 0.0003

# Scalar for the amount of karma given to an innocent upon killing a traitor.
# This is similar to karma-kill-penalty: it will reward the player with the amount of karma that would be deducted if
# doing this much damage to a teammate.
#
# Note that in Minecraft, the maximum amount of health one may have is 20 (10 hearts).
karma-traitorkill-bonus: 8

# Players will be kicked from the round once they reach or go under this karma level. (Set to -1 for no autokick.)
karma-low-autokick: 450

# Whether players should be temporarily or permanently banned instead of kicked.
karma-low-ban: false

# The duration in minutes players will be banned for upon falling below the threshold. (Set to -1 for a permanent ban.)
# Note: changing this will not retroactively apply to previously issued bans.
karma-low-ban-minutes: 60

# Whether karma will persist through restarts and disconnects.
# If false, karma will reset when the plugin is reloaded and when players leave the server.
karma-persist: true

# Whether damage is scaled based on karma. At lower karma values, players will do less damage.
karma-damage-reduction: true

# Whether karma changes less than 1 should be rounded up.
karma-round-to-one: true

# Whether karma changes should be logged to the console. Note that this will typically cause massive log spam.
karma-debug: false

###########################
# Operating Mode Settings #
###########################

# The operating mode of the plugin. Three options are available:
#     standard - Players may join rounds at will, and will be ejected from the round when it ends.
#     continuous - Players may join rounds at will, but will not be ejected when it ends.
#                  Instead, the arena will reset to its initial state and a new round will begin.
#     dedicated - Only one round will exist on the server, which players will be entered into upon connecting.
#                 After a time or round limit (whichever comes first), the server will switch to a new arena.
# If the set value is not valid, it will default to 'standard'.
operating-mode: standard

# The mode by which new arenas are selected in dedicated mode. Three options are available:
#     shuffle - Arenas will be selected in a fixed order determined by performing a random shuffle upon the arena list.
#               This order may change between restarts.
#     sequential - Arenas will be selected in a fixed order determined by the engine.
#     random - Arenas will be selected completely randomly.
# If the set value is not valid, it will default to 'sequential'.
#
# NOTE: this option will have no effect if 'operating-mode' is not set to 'dedicated'.
map-cycle-mode: shuffle

# The round limit for each arena in dedicated mode.
# After this number of rounds have taken place, the server will switch to a new arena.
# Set to -1 for no limit.
#
# NOTE: this option will have no effect if 'operating-mode' is not set to 'dedicated'.
map-cycle-round-limit: 6

# The time limit in minutes for a given arena in dedicated mode.
# After this limit is reached, the server will switch to a new arena.
# Set to -1 for no limit.
#
# NOTE: this option will have no effect if 'operating-mode' is not set to 'dedicated'.
map-cycle-time-limit: 30

# The server to return players to upon using the `/ttt leave` command in a dedicated server.
# This will only take effect if both of the following conditions are met:
#   a) the server is part of a BungeeCord network
#   b) the 'operating-mode' config key is set to 'dedicated'
return-server: ''

###################
# Plugin Settings #
###################

# Whether potentially unnecessary information should be logged.
verbose-logging: true

# The default locale used by the plugin.
# TTT will attempt to send messages to players in their respective locale, but will fall back to this if a message
# is not available in a locale. It will also be used for console messages.
locale: en_US

# Whether the plugin should update itself (highly recommended).
enable-auto-update: true

# Whether the plugin is allowed to submit anonymous usage information to bStats.
enable-metrics: true
