name: TTT
version: ${version}
main: net.caseif.ttt.TTTBootstrap
author: ${author}
api-version: 1.13
website: http://dev.bukkit.org/bukkit-plugins/ttt
description: A Bukkit minigame based off the Garry's Mod gamemode Trouble In Terrorist Town.
softdepend: [Steel]

commands:
  ttt:
    description: The plugin's primary command.
    usage: /ttt [subcommand]

permissions:
  ttt.*:
    description: Allows for full control and manipulation of the plugin.
    default: op
    children:
      ttt.use: true
      ttt.admin: true
      ttt.lobby: true

  ttt.use:
    description: Allows basic (user-level) use of the plugin.
    default: true

  ttt.admin:
    description: Allows for basic administrative use of the plugin (e.g. manipulating rounds and lobby signs, but not arenas).
    default: op
    children:
      ttt.use: true
      ttt.lobby: true

  ttt.superadmin:
    description: Allows for full administrative use of the plugin.
    default: op
    children:
      ttt.admin: true

  ttt.lobby:
    description: Allows for full usage and manipulation of lobby signs.
    default: op
    children:
      ttt.lobby.admin: true
      ttt.lobby.use: true
  ttt.lobby.*:
    description: Allows for full usage and manipulation of lobby signs.
    children:
      ttt.lobby: true
  ttt.lobby.admin:
    description: Allows creation and destruction of lobby signs.
    default: op
    children:
      ttt.lobby.create: true
      ttt.lobby.destroy: true
  ttt.lobby.use:
    description: Allows use of lobby signs.
    default: true

  # deprecated nodes
  ttt.admin.*:
    description: Allows for full administrative use of the plugin.
    children:
      ttt.admin: true
